channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- cudatoolkit=10.2
- cudnn=7.6.5
- scikit-learn
- scipy=1.7
- h5py=2.10.0
- uproot
- matplotlib
- pandas
- numba
- ipython
- pip:
  - absl-py==1.4.0
  - astunparse==1.6.3
  - cachetools==5.3.1
  - certifi==2023.5.7
  - charset-normalizer==3.1.0
  - conda-pack==0.7.1
  - gast==0.3.3
  - google-auth==2.21.0
  - google-auth-oauthlib==1.0.0
  - google-pasta==0.2.0
  - grpcio==1.56.0
  - idna==3.4
  - importlib-metadata==6.7.0
  - keras-preprocessing==1.1.2
  - markdown==3.4.3
  - markupsafe==2.1.3
  - numpy==1.18.5
  - oauthlib==3.2.2
  - opt-einsum==3.3.0
  - protobuf==3.20.0
  - pyasn1==0.5.0
  - pyasn1-modules==0.3.0
  - pyyaml==6.0.2
  - requests==2.31.0
  - requests-oauthlib==1.3.1
  - rsa==4.9
  - scipy==1.4.1
  - tensorboard==2.13.0
  - tensorboard-data-server==0.7.1
  - tensorflow==2.3.0
  - tensorflow-estimator==2.3.0
  - urllib3==1.26.16
  - werkzeug==2.3.6
  - wrapt==1.15.0
  - zipp==3.15.0
